3 To - Do - Task
Please Complete all the problem listed below.
3.1 Warm Up Exercises:
1. Sorting and Subsetting:
Complete all following Task:
• Dataset for the Task: "titanic.csv"
Following task is common for all the problem:
1. Load the provided dataset and import in pandas DataFrame.
2. Check info of the DataFrame and identify following:

In [1]:
import pandas as pd
import numpy as np

titanic = pd.read_csv("titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Problem 1 - Sorting:
1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.
2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.
3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [2]:
# 1. Create DataFrame with only Fare
fare = titanic[["Fare"]]
fare.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

In [3]:
# 2. Create DataFrame with Pclass and Age
class_age = titanic[["Pclass", "Age"]]
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [4]:
# 3. Create DataFrame with Survived and Sex
survived_gender = titanic[["Survived", "Sex"]]
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

Problem - 2 - Subsetting:
Complete all the following Task:
Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.
2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.
3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [6]:
# 1. Filter: Fare > 100
fare_gt_100 = titanic[titanic["Fare"] > 100]
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [7]:
# 2. Filter: Pclass = 1
first_class = titanic[titanic["Pclass"] == 1]
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [8]:
# 3. Filter: female under 18
female_under_18 = titanic[(titanic["Age"] < 18) & (titanic["Sex"] == "female")]
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

Subsetting Rows by Categorical variables:
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.
2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [9]:
# 1. Embarked = C or S
embarked_c_or_s = titanic[titanic["Embarked"].isin(["C","S"])]
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
# 2. Pclass in [1,2]
first_second_class = titanic[titanic["Pclass"].isin([1,2])]
first_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

3.2 Exploratory Data Analysis Practice Exercise - 1.
Warning: Handle missing values in the Age column by filling them with the median age of

the dataset before performing the division.)

Answer the following questions from Dataset:
Which passenger had the highest fare paid relative to their age?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).
2. Subset rows where fare per year is higher than 5, assigning this to high fare age.
3. Sort high fare age by descending fare per year, assigning this to high fare age srt.
4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.

In [11]:
titanic["Age"] = titanic["Age"].fillna(titanic["Age"].median())

In [12]:
# 1: Add fare_per_year
titanic["fare_per_year"] = titanic["Fare"] / titanic["Age"]
titanic[["Name", "Fare", "Age", "fare_per_year"]].head()

,Name,Fare,Age,fare_per_year
0,"Braund, Mr. Owen Harris",7.2500,22.0,0.329545
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,38.0,1.875876
2,"Heikkinen, Miss. Laina",7.9250,26.0,0.304808
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,35.0,1.517143
4,"Allen, Mr. William Henry",8.0500,35.0,0.230000

In [13]:
# 2: Subset fare_per_year > 5
high_fare_age = titanic[titanic["fare_per_year"] > 5]
high_fare_age.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare_per_year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,B78,C,5.232886
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733

In [14]:
# 3: Sort descending
high_fare_age_srt = high_fare_age.sort_values("fare_per_year", ascending=False)

result_1 = high_fare_age_srt[["Name", "fare_per_year"]]
result_1.head()

                                Name  fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

In [15]:
# 4: Add fare_per_class
titanic["fare_per_class"] = titanic["Fare"] / titanic["Pclass"]
titanic[["Name", "Fare", "Pclass", "fare_per_class"]].head()

,Name,Fare,Pclass,fare_per_class
0,"Braund, Mr. Owen Harris",7.2500,3,2.416667
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,1,71.283300
2,"Heikkinen, Miss. Laina",7.9250,3,2.641667
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,1,53.100000
4,"Allen, Mr. William Henry",8.0500,3,2.683333

In [32]:
# 5
print(result_1.head())

                                Name  fare_per_year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.
2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.
3. Sort adult males by descending fare per class, assigning this to adult males srt.
4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [17]:
# 1: Add fare_per_class
titanic["fare_per_class"] = titanic["Fare"] / titanic["Pclass"]

In [18]:
# 2: Filter adult males
adult_males = titanic[(titanic["Sex"] == "male") & (titanic["Age"] >= 18)]

In [19]:
#  3: Sort by fare_per_class
adult_males_srt = adult_males.sort_values("fare_per_class", ascending=False)

In [20]:
# 4: Select required columns
result = adult_males_srt[["Name", "Age", "fare_per_class"]]

In [21]:
# Step 5: Look at the result
result.head()

                                   Name   Age  fare_per_class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
27       Fortune, Mr. Charles Alexander  19.0        263.0000
438                   Fortune, Mr. Mark  64.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:
Based on the dataset Answer the following question:
What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.
2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.
3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).
4. Combine the fare totals from first, second, and third classes into a list.
5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [22]:
#  1: Total fare revenue
total_fare = titanic["Fare"].sum()

In [23]:
#  2: Fare from first class
fare_class1 = titanic[titanic["Pclass"] == 1]["Fare"].sum()

In [24]:
# 3: Fare from second class
fare_class2 = titanic[titanic["Pclass"] == 2]["Fare"].sum()

In [25]:
# 4: Fare from third class
fare_class3 = titanic[titanic["Pclass"] == 3]["Fare"].sum()

In [26]:
# 5: Calculate percentage contribution
fare_percentages = [
    (fare_class1 / total_fare) * 100,
    (fare_class2 / total_fare) * 100,
    (fare_class3 / total_fare) * 100
]

fare_percentages

[np.float64(63.349287718996564),
 np.float64(13.24962855496507),
 np.float64(23.401083726038365)]

What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?
To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18(64), and "senior" (age 65 and above).
2. Calculate the total number of passengers on the Titanic.
3. Count the number of passengers in each age group.
4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.
5. Display the proportion as a percentage.

In [28]:
# 1: Create age_group column
def age_group(age):
    if age < 18:
        return "child"
    elif age < 65:
        return "adult"
    else:
        return "senior"

titanic["age_group"] = titanic["Age"].apply(age_group)
print("Added new column 'age_group'")

Added new column 'age_group'

In [29]:
# 2: Total number of passengers
total_passengers = len(titanic)
print("Total Passengers:", total_passengers)

Total Passengers: 891

In [30]:
# 3: Count per group
age_group_counts = titanic["age_group"].value_counts()
print("\nPassenger Count by Age Group:")
print(age_group_counts)

Passenger Count by Age Group:
age_group
adult     767
child     113
senior     11
Name: count, dtype: int64

In [31]:
# 4: Percentages
age_group_percentages = (age_group_counts / total_passengers) * 100
print("\nPercentage by Age Group:")
print(age_group_percentages)

Percentage by Age Group:
age_group
adult     86.083053
child     12.682379
senior     1.234568
Name: count, dtype: float64